version: '3.8'

services:
  data-collection:
    build:
      context: ./data-collection
      dockerfile: Dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
      - ./config.json:/usr/src/app/dist/config.json
    env_file:
      - .env

  decision-making:
      build:
        context: ./decision-making
        dockerfile: Dockerfile
      volumes:
        - ./logs:/usr/src/app/logs
        - ./config.json:/usr/src/app/config.json
      env_file:
        - .env
      depends_on:
        - data-collection