version: '3.8'

services:
  data-collection:
    build:
      context: ./data-collection
      dockerfile: Dockerfile
    volumes:
      - ./logs:/usr/src/logs/
      - ./config.json:/usr/src/app/config.json
    env_file:
      - .env
    restart: always

  # decision-making:
  #     build:
  #       context: ./decision-making
  #       dockerfile: Dockerfile
  #     volumes:
  #       - ./logs:/usr/src/app/logs
  #       - ./config.json:/usr/src/app/config.json
  #     env_file:
  #       - .env
  #     restart: always
  #     depends_on:
  #       - data-collection